// <auto-generated />
using System;
using CarsShowroom.DataAccess.DataContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CarsShowroom.DataAccess.Migrations
{
    [DbContext(typeof(ShowroomDbContext))]
    partial class ShowroomDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CarsShowroom.DataAccess.ContextEntities.ExtraItemEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("Count")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<long?>("ShowroomEntityId")
                        .HasColumnType("bigint");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<long>("VehicleModelEntityKey")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ShowroomEntityId");

                    b.HasIndex("VehicleModelEntityKey");

                    b.HasIndex("Name", "VehicleModelEntityKey")
                        .IsUnique();

                    b.HasIndex("Name", "VehicleModelEntityKey", "Type")
                        .IsUnique();

                    b.ToTable("ExtraItems");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Count = 10,
                            Name = "Harman Kardon audio system",
                            Price = 185000m,
                            Type = 1,
                            VehicleModelEntityKey = 1L
                        },
                        new
                        {
                            Id = 4L,
                            Count = 10,
                            Name = "Power Wilkins Audio system",
                            Price = 160000m,
                            Type = 1,
                            VehicleModelEntityKey = 2L
                        },
                        new
                        {
                            Id = 5L,
                            Count = 3,
                            Name = "19R Alpine wheels set",
                            Price = 750000m,
                            Type = 2,
                            VehicleModelEntityKey = 2L
                        },
                        new
                        {
                            Id = 6L,
                            Count = 3,
                            Name = "AMG kit",
                            Price = 300000m,
                            Type = 2,
                            VehicleModelEntityKey = 3L
                        },
                        new
                        {
                            Id = 7L,
                            Count = 3,
                            Name = "Ceramic breaks system",
                            Price = 915000m,
                            Type = 2,
                            VehicleModelEntityKey = 4L
                        },
                        new
                        {
                            Id = 2L,
                            Count = 10,
                            Name = "Lip spoiler",
                            Price = 45000m,
                            Type = 2,
                            VehicleModelEntityKey = 1L
                        },
                        new
                        {
                            Id = 3L,
                            Count = 10,
                            Name = "LED lights",
                            Price = 310000m,
                            Type = 1,
                            VehicleModelEntityKey = 1L
                        });
                });

            modelBuilder.Entity("CarsShowroom.DataAccess.ContextEntities.ReceiptEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("ShowroomKey")
                        .HasColumnType("bigint");

                    b.Property<int>("TotalItemsCount")
                        .HasColumnType("integer");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("ShowroomKey");

                    b.ToTable("Receipts");
                });

            modelBuilder.Entity("CarsShowroom.DataAccess.ContextEntities.ShowroomEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContactNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Showrooms");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Address = "Ростов-на-Дону, ул. Еременко 28, 'BMW Motors'",
                            ContactNumber = "79959303330"
                        },
                        new
                        {
                            Id = 2L,
                            Address = "Ростов-на-Дону, ул. Шаболдаева 105, 'Mercedes-Benz club'",
                            ContactNumber = "79959303331"
                        });
                });

            modelBuilder.Entity("CarsShowroom.DataAccess.ContextEntities.SoldExtraItemsEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("Count")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<long?>("ReceiptEntityId")
                        .HasColumnType("bigint");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<string>("VehicleModelKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ReceiptEntityId");

                    b.HasIndex("VehicleModelKey");

                    b.ToTable("SoldExtraItemsEntity");
                });

            modelBuilder.Entity("CarsShowroom.DataAccess.ContextEntities.SoldVehicleEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Color")
                        .HasColumnType("integer");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<long>("ReceiptKey")
                        .HasColumnType("bigint");

                    b.Property<DateOnly>("ReleaseDate")
                        .HasColumnType("date");

                    b.Property<string>("Vin")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ReceiptKey")
                        .IsUnique();

                    b.ToTable("SoldVehicleEntity");
                });

            modelBuilder.Entity("CarsShowroom.DataAccess.ContextEntities.VehicleEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Color")
                        .HasColumnType("integer");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<DateOnly>("ReleaseDate")
                        .HasColumnType("date");

                    b.Property<long>("ShowroomEntityKey")
                        .HasColumnType("bigint");

                    b.Property<long>("VehicleModelId")
                        .HasColumnType("bigint");

                    b.Property<string>("Vin")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ShowroomEntityKey");

                    b.HasIndex("VehicleModelId");

                    b.HasIndex("Brand", "VehicleModelId", "Color")
                        .IsUnique();

                    b.ToTable("Vehicles");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Brand = "BMW",
                            Color = 4,
                            Price = 2350000m,
                            ReleaseDate = new DateOnly(2015, 1, 1),
                            ShowroomEntityKey = 1L,
                            VehicleModelId = 1L,
                            Vin = "23D34EC8-F83F-4BED-95D6-05BDE4F76222"
                        },
                        new
                        {
                            Id = 2L,
                            Brand = "BMW",
                            Color = 3,
                            Price = 3200000m,
                            ReleaseDate = new DateOnly(2017, 6, 13),
                            ShowroomEntityKey = 1L,
                            VehicleModelId = 1L,
                            Vin = "6786D736-1C1D-4375-8A35-6594E5133823"
                        },
                        new
                        {
                            Id = 3L,
                            Brand = "BMW",
                            Color = 3,
                            Price = 10200000m,
                            ReleaseDate = new DateOnly(2020, 11, 1),
                            ShowroomEntityKey = 1L,
                            VehicleModelId = 2L,
                            Vin = "8E10D3F9-FE4A-4023-9E44-505249AE95C5"
                        },
                        new
                        {
                            Id = 4L,
                            Brand = "Mercedes-Benz",
                            Color = 1,
                            Price = 3200000m,
                            ReleaseDate = new DateOnly(2016, 5, 10),
                            ShowroomEntityKey = 2L,
                            VehicleModelId = 3L,
                            Vin = "80070953-A133-41C2-AD49-BD51C30FC7AE"
                        },
                        new
                        {
                            Id = 5L,
                            Brand = "Mercedes-Benz",
                            Color = 5,
                            Price = 9450000m,
                            ReleaseDate = new DateOnly(2018, 3, 12),
                            ShowroomEntityKey = 2L,
                            VehicleModelId = 4L,
                            Vin = "BCC89D79-35D9-4AC2-8597-A837DED42699"
                        });
                });

            modelBuilder.Entity("CarsShowroom.DataAccess.ContextEntities.VehicleModelEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Model")
                        .IsUnique();

                    b.ToTable("VehicleModels");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Model = "BMW 325"
                        },
                        new
                        {
                            Id = 2L,
                            Model = "BMW M5 F90"
                        },
                        new
                        {
                            Id = 3L,
                            Model = "Mercedes-Benz E200"
                        },
                        new
                        {
                            Id = 4L,
                            Model = "Mercedes-Benz CLS63 AMG"
                        });
                });

            modelBuilder.Entity("CarsShowroom.DataAccess.ContextEntities.ExtraItemEntity", b =>
                {
                    b.HasOne("CarsShowroom.DataAccess.ContextEntities.ShowroomEntity", null)
                        .WithMany("ExtraItems")
                        .HasForeignKey("ShowroomEntityId");

                    b.HasOne("CarsShowroom.DataAccess.ContextEntities.VehicleModelEntity", "VehicleModelEntity")
                        .WithMany("ExtraItems")
                        .HasForeignKey("VehicleModelEntityKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VehicleModelEntity");
                });

            modelBuilder.Entity("CarsShowroom.DataAccess.ContextEntities.ReceiptEntity", b =>
                {
                    b.HasOne("CarsShowroom.DataAccess.ContextEntities.ShowroomEntity", "Showroom")
                        .WithMany("Receipts")
                        .HasForeignKey("ShowroomKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Showroom");
                });

            modelBuilder.Entity("CarsShowroom.DataAccess.ContextEntities.SoldExtraItemsEntity", b =>
                {
                    b.HasOne("CarsShowroom.DataAccess.ContextEntities.ReceiptEntity", null)
                        .WithMany("SoldExtraItems")
                        .HasForeignKey("ReceiptEntityId");

                    b.HasOne("CarsShowroom.DataAccess.ContextEntities.VehicleModelEntity", "VehicleModel")
                        .WithMany()
                        .HasForeignKey("VehicleModelKey")
                        .HasPrincipalKey("Model")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VehicleModel");
                });

            modelBuilder.Entity("CarsShowroom.DataAccess.ContextEntities.SoldVehicleEntity", b =>
                {
                    b.HasOne("CarsShowroom.DataAccess.ContextEntities.ReceiptEntity", "Receipt")
                        .WithOne("SoldVehicle")
                        .HasForeignKey("CarsShowroom.DataAccess.ContextEntities.SoldVehicleEntity", "ReceiptKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Receipt");
                });

            modelBuilder.Entity("CarsShowroom.DataAccess.ContextEntities.VehicleEntity", b =>
                {
                    b.HasOne("CarsShowroom.DataAccess.ContextEntities.ShowroomEntity", "Showroom")
                        .WithMany("Vehicles")
                        .HasForeignKey("ShowroomEntityKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CarsShowroom.DataAccess.ContextEntities.VehicleModelEntity", "VehicleModelEntity")
                        .WithMany()
                        .HasForeignKey("VehicleModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Showroom");

                    b.Navigation("VehicleModelEntity");
                });

            modelBuilder.Entity("CarsShowroom.DataAccess.ContextEntities.ReceiptEntity", b =>
                {
                    b.Navigation("SoldExtraItems");

                    b.Navigation("SoldVehicle")
                        .IsRequired();
                });

            modelBuilder.Entity("CarsShowroom.DataAccess.ContextEntities.ShowroomEntity", b =>
                {
                    b.Navigation("ExtraItems");

                    b.Navigation("Receipts");

                    b.Navigation("Vehicles");
                });

            modelBuilder.Entity("CarsShowroom.DataAccess.ContextEntities.VehicleModelEntity", b =>
                {
                    b.Navigation("ExtraItems");
                });
#pragma warning restore 612, 618
        }
    }
}
